eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://registry:8000/eureka/}      
spring:
  boot:
    admin:
      client:
        url: http://admin:8000
        username: admin
        password: admin
  rabbitmq:
    addresses: amqps://hvifsdtz:CkikAY7BrnXSjbppG4yMmLFV8mtPXzjo@finch.rmq.cloudamqp.com/hvifsdtz
microservices:
  endpoints:
    endpoint:
      airline:
        getAirlineByName: http://airline-service/airline/getAirlineByName
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    mongo:
      enabled: false
server:
  port: 8000

