
spring:
  mongodb:
    uri: mongodb://root:example@mongo/assignment_user?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false&maxPoolSize=50&connectTimeoutMS=2000
    database: userAssignment
  cloud:
    gateway:
      routes:
        - id: product-catalog-service
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-catalog-service
                fallbackuri: forward:/productFallback
        - id: price-service
          uri: lb://price-service
          predicates:
            - Path=/api/prices/**
          filters:
            - name: CircuitBreaker
              args:
                name: price-service
                fallbackuri: forward:/priceFallback
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - name: CircuitBreaker
              args:
                name: cart-service
                fallbackuri: forward:/cartFallback
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderFallback
hystrix:
  command:
    fallback:
      isolation:
        thread:
          timeoutInMilliseconds: 5000   
          
management:
  security:
    enabled: false 
  endpoints:
    web:
      exposure:
        include: "*"
