
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: airline-service
          uri: lb://AIRLINE-SERVICE
          predicates:
            - Path=/airline/**
          filters:
            - name: CircuitBreaker
              args:
                name: airline-service
                fallbackuri: forward:/airlineFallback
        - id: flight-service
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/flight/**
          filters:
            - name: CircuitBreaker
              args:
                name: airline-service
                fallbackuri: forward:/flightFallback
hystrix:
  command:
    fallback:
      isolation:
        thread:
          timeoutInMilliseconds: 5000   
          
management:
  security:
    enabled: false 
  endpoints:
    web:
      exposure:
        include: hystrix.stream
