hibernate:
  ogm:
    datastore:
      create_database: true
      database: Assignment
      host: mongo
      password: example
      port: 27017
      provider: mongodb
      username: root
    mongodb:
      authentication_database: admin
